# Numpy operation in puthon with jupyter notebook

In [4]:
#### import numpy

In [8]:
import numpy as np

#### combining arrays

#### Horizontal stack(hstack)

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])

result = np.hstack((a,b))
print(result)

[1 2 3 4 5 6]


#### vertical stack(Ustack)

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])

result = np.vstack((a,b))
print(result)

[[1 2 3]
 [4 5 6]]


#### spliting arrays

In [13]:
arr = np.array([1,2,3,4,5,6])
result = np.split(arr,2)
print(result)

[array([1, 2, 3]), array([4, 5, 6])]


## search function

#### find index

In [14]:
arr = np.array([10,20,30,40,50])
index = np.where(arr == 30)
print(index)


(array([2]),)


#### search sorted position

In [23]:
arr = np.array([10,20,30,40,50])
position = np.searchsorted(arr,25)
print(position)

2


#### sort function

In [26]:
arr = np.array([10,20,30,40,50])
print(np.sort(arr))

[10 20 30 40 50]


## Aggregation & statistical function

In [30]:
arr = np.array((10,20,30,40,50))
print("sum:",np.sum(arr))
print("mean:",np.mean(arr))
print("median:",np.median(arr))
print("max:",np.max(arr))
print("min:",np.min(arr))

sum: 150
mean: 30.0
median: 30.0
max: 50
min: 10


#### Filter arrays(Bolean indexing)

In [31]:
arr = np.array([10,20,30,40,50])
result = arr[arr < 35]
print(result)

[10 20 30]


#### Multiple condition

In [32]:
arr = np.array([10,20,30,40,50])
result = arr[(arr > 20)&(arr < 50)]
print(result)

[30 40]


#### Masking arrays

In [34]:
arr = np.array ([10,20,30,40,50])
mask = arr > 30
print(mask)

[False False False  True  True]


In [35]:
filtered = arr[mask]
print(filtered)

[40 50]


#### Reshaping arrays

##### convert array dimention without changing data.

In [37]:
# 1D to 3D
arr = np.array([10,20,30,40,50,60,70,80])
result = arr.reshape(2,2,2)
print(result)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [38]:
# 1D to 2D
arr = np.array([10,20,30,40,50,60])
result = arr.reshape(2,3)
print(result)

[[10 20 30]
 [40 50 60]]


In [39]:
arr = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
result = arr.reshape(8)
print(result)

[10 20 30 40 50 60 70 80]


#### Array broadcasting

In [40]:
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])

result = a+b
print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]
